### ISSUE TITLE
新入社員教育

### ISSUE THREAD

**Issue by JungSungHo** [JungSungHo/Vue-Tutorial#1]
## Task

- First Time[0:30:00]
  - [x] VueJsの概要：https://github.com/JungSungHo/Vue-Tutorial/wiki/Vue-Concepts
  - [x] 基礎から学ぶVue js 3 [22:18]：https://www.youtube.com/watch?v=wlCwyouRbtE

- Second Time[1:30:00]
  - [x] Vue.jsでタイピングゲームをつくってみよう！：https://www.youtube.com/watch?v=dP652Gi_57k
    - Tutorial2：https://github.com/JungSungHo/Vue-Tutorial/pull/3

- Third Time[1:00:00]
  - [x] 環境設定：  https://github.com/JungSungHo/Vue-Tutorial/wiki/Vue-Configuration
  - [x] Tutorial1：https://github.com/JungSungHo/Vue-Tutorial/pull/2
  - [x] Q&A

**Comment by JungSungHo** [comment]
5/16 教育終了しましたので、クローズします。
